
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: standalone_rabbitmq
    env_file:
      - .env
    ports:
      - "${RABBITMQ_NODE_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - shared_network

volumes:
  rabbitmq_data:
    driver: local

networks:
  shared_network:
    driver: bridge
    name: my_shared_network